BridgeDigitalHealth/open-bridge-web

src/components/studies/LiveIcon.tsx
src/components/studies/StudyList.tsx
src/components/widgets/ConfirmationDialog.tsx

Changed font to match design on Figma

Minor Font Changes

---

src/components/studies/StudyBuilder.tsx
src/components/studies/session-creator/SessionCreator.tsx

ability to save from study builder & disable navigation to the same section

---

src/components/studies/session-creator/SessionActionButtons.tsx
src/components/widgets/StyledComponents.tsx
src/style/theme.ts

refactor of session action buttons to take advance to shared styles

---

src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx

text area fix for scheduler

---

src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/ParticipantTableGrid.tsx
src/components/studies/participants/ParticipantTablePagination.tsx

smooth out grid loading

---

src/__tests__/components/studies/participants/ParticipantSearch.test.tsx
src/components/studies/participants/ParticipantSearch.tsx

Search for a participant using ID when the enter key is pressed. Added tests to the search participant functionality.
Resolves #94

Search for participant on enter key press.

---

src/components/assessments/AssessmentDetail.tsx

Adjusted padding of Assessment Details Screen

---

src/assets/chevron_down_icon.svg
src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/LeadInvestigatorDropdown.tsx
src/components/widgets/StyledComponents.tsx
src/style/theme.ts
src/types/types.ts

Restyled App Design page based on requests from Lynn.

Restyle App Design Page

---

src/App.tsx
src/AuthenticatedApp.tsx
src/components/access-settings/AccountListing.tsx
src/components/account/AccountLogin.tsx
src/components/studies/StudyList.tsx
src/components/widgets/AppTopNav.tsx
src/helpers/AuthContext.tsx
src/routes_private.ts
src/style/theme.ts
src/types/types.ts

https://sagebionetworks.jira.com/browse/MTB-111

Logout experience

---

src/components/studies/StudyCard.tsx
src/components/studies/StudyList.tsx
src/types/types.ts

Added a blue border to study cards when the user hovers over them. Also, set the blue border to appear on newly created study cards for only 600ms.

Added blue border as hover state to study card

---

src/assets/chevron_down_icon.svg
src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/LeadInvestigatorDropdown.tsx

Made dropdown from Material UI components 

---

src/components/studies/StudyBuilder.tsx
src/components/studies/scheduler/Duration.tsx
src/components/studies/scheduler/IntroInfo.tsx
src/components/studies/scheduler/Scheduler.tsx
src/components/studies/scheduler/StudyStartDate.tsx

Page now looks like this:
Resolves #121

Restyled Study Without Scheduling Page 

---

src/components/studies/participants/ParticipantManager.tsx

When a user is not found, the page no longer crashes:

Fixed crashing issue with participant search

---

src/components/studies/app-design/LeadInvestigatorDropdown.tsx
src/components/studies/scheduler/Timeline.tsx
src/components/widgets/BlackBorderDropdown.tsx

It appears that we are using the that style of the dropdown in other parts of the app. So I have created a generic presentational component in widgets to simplify the use.
I have updated the leadInvestigaor control to use it.
Please take a look and let me know if you see any issues.

refactor black border dropdown into its own component

---

src/components/studies/scheduler/NotificationTime.tsx
src/components/studies/scheduler/RepeatFrequency.tsx
src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx
src/components/studies/scheduler/Scheduler.tsx
src/components/studies/scheduler/Timeline.tsx
src/components/studies/scheduler/TimelineCustomPlot.tsx

updates to scheduler and fixes in graph

simplify error handling in scheduler

---

src/components/studies/launch/IrbDetails.tsx

Error is displayed when the expiration date is before the approval date.
Looks like:

Added Asterisk to fields and error message for approval date validation

---

src/components/studies/passive-features/PassiveFeatures.tsx
src/components/studies/sections.ts

Reordered left nav and added text to passive features section.

---

src/components/studies/app-design/StudySummarySection.tsx

Make body copy required.

---

src/components/studies/scheduler/NotificationWindow.tsx
src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx
src/components/studies/scheduler/Scheduler.tsx

Added notification errors

---

src/components/studies/scheduler/IntroInfo.tsx

Added weekly information text to info page.

---

src/assets/preview/sample_assessment_data.svg
src/components/studies/StudyBuilder.tsx
src/components/studies/preview/Preview.tsx

Preview Study Screen Updates.

---

src/components/studies/launch/LaunchAlerts.tsx
src/components/studies/scheduler/utility.ts

If you want to try it out, I added the following code into the `scheduler.tsx` file:
` 
<button
onClick={() => {
const isSame = isSameAsDefaultSchedule(_schedule)
alert('same as default ' + isSame)
}}
style={{ width: '40px', height: '40px', backgroundColor: 'red' }}
></button>
`
Also added this as an optional alert to launch alerts.

Added function and alert that checks if the schedule is default

---

src/components/studies/participants/ParticipantManager.tsx

Only display number of participants for selected tab

---

src/components/studies/StudyBuilder.tsx
src/components/studies/launch/IrbDetails.tsx
src/components/studies/launch/LaunchStepper.tsx
src/components/studies/participants/ParticipantManager.tsx
src/types/types.ts

Persists information regarding the start/end dates:

Update IRB Fields on the study object

---

src/components/studies/scheduler/AssessmentList.tsx

Style session assessments

---

src/components/access-settings/AccessGrid.tsx
src/components/access-settings/AccessSettings.tsx
src/components/access-settings/MemberInvite.tsx

Page now looks like:
Resolves: #207

Added Access Settings

---

src/components/studies/StudyCard.tsx
src/services/participants.service.ts

If the study is out of the design phase, then display the number of enrolled participants:

Display Real Number of Participants

---

src/components/access-settings/AccessGrid.tsx
src/components/access-settings/AccessSettings.tsx
src/components/access-settings/AccountListing.tsx
src/components/access-settings/MemberInvite.tsx
src/helpers/utility.ts

Collaborator is allowed to see access settings info but not edit it:
Resolves: #209

Add collaborator view

---

src/components/studies/scheduler/AssessmentWindow.tsx

Deleted persistent mode checkbox

---

src/components/access-settings/AccessGrid.tsx
src/components/access-settings/AccessSettings.tsx
src/components/studies/participants/ParticipantManager.tsx
src/services/participants.service.ts
src/types/types.ts

- show withdrawn for test users

updates to participant search

---

src/components/access-settings/AccountListing.tsx
src/components/studies/StudyCard.tsx
src/components/studies/participants/ParticipantManager.tsx
src/components/studies/preview/Preview.tsx
src/helpers/utility.ts

Formats all studyids to take the form: xxx-xxx. If the study id is not a string with length 6, do nothing.
Looks like:

Format the study id

---

src/components/assessments/AssessmentImage.tsx
src/components/studies/scheduler/Timeline.tsx

Display assessments on timeline legend hover

---

src/components/studies/session-creator/SessionActionButtons.tsx
src/components/studies/session-creator/SessionCreator.tsx

https://sagebionetworks.jira.com/browse/MTB-174

name when duplicating a session

---

src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx
src/components/studies/scheduler/SchedulingFormSection.tsx
src/services/study.service.ts

https://sagebionetworks.jira.com/browse/MTB-172

Update to session notifications

---

src/components/studies/launch/Live.tsx

Looks Like:
Resolves: https://sagebionetworks.jira.com/browse/MTB-178

Restyled Live Page

---

src/components/studies/launch/AboutStudy.tsx
src/components/studies/scheduler/IntroInfo.tsx

1. Changed text and styling of text on the about study page:
2. Changed study duration description:
Resolves: https://sagebionetworks.jira.com/browse/MTB-173, https://sagebionetworks.jira.com/browse/MTB-156

Jira Issues 156 + 173

---

src/components/studies/StudyBuilder.tsx
src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/StudyPageTopPhoneContent.tsx
src/components/studies/app-design/UploadStudyLogoSection.tsx
src/services/study.service.ts
src/types/types.ts

Add ability to upload a logo in the customize app tab

---

src/components/studies/session-creator/SingleSessionContainer.tsx

1. Updated the trash can when the edit mode is on:
2. Update the way the scrollbar looks:

Session Creator Styling

---

src/assets/scheduler/floating_save_icon.svg
src/components/studies/scheduler/Scheduler.tsx
src/components/widgets/SaveButton.tsx

Added floating save button to scheduler

---

src/components/studies/participants/ParticipantManager.tsx
src/services/participants.service.ts

Search for participants in a study based on external_id and phone number.

Update search functionality

---

src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/StudyLeadInformationSection.tsx

1. Removed Asterisk from Funder:
2. Set using default message to true by default

Jira Issue 180

---

src/components/studies/StudyBuilder.tsx
src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/GeneralContactAndSupportSection.tsx
src/components/studies/app-design/IrbBoardContactSection.tsx
src/components/studies/app-design/LeadInvestigatorDropdown.tsx
src/components/studies/app-design/StudyLeadInformationSection.tsx
src/components/studies/app-design/StudyPageBottomPhoneContent.tsx
src/components/studies/app-design/StudyPageTopPhoneContent.tsx
src/components/studies/app-design/StudySummarySection.tsx
src/components/studies/app-design/TextInputWrapper.tsx
src/components/studies/launch/LaunchAlerts.tsx
src/components/widgets/BlackBorderDropdown.tsx
src/helpers/utility.ts
src/types/constants.ts

1. Allow for partial editing of the fields
2. Display errors only when coming from the launch page.

Edit Customize App Page

---

src/components/studies/app-design/AppDesign.tsx
src/components/studies/launch/LaunchAlerts.tsx

Scroll to section of error when user comes from launch page to AppDesign.

Added Scrolling To Error

---

public/participantImport_id_template.csv
public/participantImport_phone_template.csv
src/components/studies/participants/AddParticipants.tsx
src/components/studies/participants/DialogContents.tsx
src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/ParticipantSearch.tsx

Error handing regarding .csv download/imports.

Fix csv import/export issues

---

src/components/access-settings/AccessGrid.tsx
src/components/access-settings/AccessSettings.tsx
src/services/access.service.ts

Fixed access settings bug and also made minor style changes.
Resolves #270

Fixed Access Settings Bug

---

src/components/studies/session-creator/SingleSessionContainer.tsx
src/components/widgets/EditableTextbox.tsx

Cap session title at 18 characters

---

src/components/studies/StudyBuilder.tsx
src/components/studies/session-creator/SessionCreator.tsx
src/components/studies/session-creator/SingleSessionContainer.tsx
src/components/studies/session-creator/read-only-pages/ReadOnlySessionCreator.tsx

Added read only session creator page

---

src/components/studies/StudyBuilder.tsx
src/components/studies/passive-features/PassiveFeatures.tsx

Added read only passive features section

---

src/components/studies/StudyBuilder.tsx
src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/StudyPageBottomPhoneContent.tsx
src/components/studies/app-design/StudyPageTopPhoneContent.tsx
src/components/studies/app-design/WelcomeScreenPhoneContent.tsx
src/components/studies/app-design/read-only-pages/ReadOnlyAppDesign.tsx

Added read only customize app page

---

src/components/studies/StudyBuilder.tsx
src/components/studies/launch/IrbDetails.tsx
src/components/studies/launch/Launch.tsx
src/components/studies/launch/read-only-components/ReadOnlyIrbDetails.tsx
src/components/studies/launch/read-only-components/ReadOnlyTextbox.tsx

Looks like:
When the Study is live:

Added Read Only Launch Page

---

src/assets/study-builder-icons/left_nav_close_icon.svg
src/assets/study-builder-icons/left_nav_open_icon.svg
src/components/studies/StudyLeftNav.tsx

Restyle left nav drawer button.

---

src/components/studies/scheduler/IntroInfo.tsx

Restyle Initial Session Creator Page

---

src/components/studies/launch/diseases.ts

Add healthy adults to the disease list.

---

src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/WelcomeScreenPhoneContent.tsx

Restyle App Design Welcome Screen

---

src/components/access-settings/AccessSettings.tsx
src/components/access-settings/AccountListing.tsx

Edited Left Panel Access Setting

---

src/components/access-settings/AccessGrid.tsx
src/components/access-settings/AccessSettings.tsx

Add Study Admin Text

---

src/components/assessments/AssessmentCard.tsx
src/components/assessments/AssessmentLibraryWrapper.tsx
src/components/studies/launch/Launch.tsx
src/components/studies/session-creator/AssessmentSelector.tsx
src/components/studies/session-creator/SessionCreator.tsx

Assessment Selector Modal Cleanup

---

src/components/studies/app-design/AppDesign.tsx
src/components/studies/launch/LaunchAlerts.tsx

Add Ability to Enter Hex into Color Picker

---

src/components/studies/StudyBuilder.tsx
src/components/studies/StudyCard.tsx
src/components/studies/StudyList.tsx
src/components/studies/launch/Launch.tsx
src/services/study.service.ts
src/types/types.ts

Centralize study phase determination

---

src/components/studies/launch/AboutStudy.tsx
src/components/widgets/BlackBorderDropdown.tsx

1. Add padding to dropdown:
2. Show more than two diseases:

Edits to launch page

---

src/components/studies/preview/Preview.tsx

Changes to preview study screen

---

src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/StudyLeadInformationSection.tsx

Link access settings in App Design.

---

src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/UploadStudyLogoSection.tsx

Reworded image compression text and also set isUsingDefaultMessage to true the first time the user visits the AppDesign page.

Customize app rewording

---

src/components/studies/StudyBuilder.tsx
src/components/studies/scheduler/Duration.tsx

Make sure all inputs allow for 3 digits and expand background color of study builder

---

src/components/studies/enrollment-type-selector/EnrollmentTypeSelector.tsx

Deleted sms option

---

src/components/widgets/AppTopNav.tsx
src/helpers/AuthContext.tsx

Redo login button logic

---

src/components/studies/BannerInfo.ts
src/components/studies/NavButtons.tsx
src/components/studies/StudyBuilder.tsx
src/components/studies/StudyLeftNav.tsx
src/components/studies/app-design/AppDesign.tsx
src/components/studies/enrollment-type-selector/EnrollmentTypeSelector.tsx
src/components/studies/launch/Launch.tsx
src/components/studies/passive-features/PassiveFeatures.tsx
src/components/studies/preview/Preview.tsx
src/components/studies/scheduleHooks.ts
src/components/studies/scheduler/Duration.tsx
src/components/studies/scheduler/IntroInfo.tsx
src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx
src/components/studies/scheduler/ScheduleCreatorTab.tsx
src/components/studies/scheduler/ScheduleTimeline.tsx
src/components/studies/scheduler/Scheduler.tsx
src/components/studies/scheduler/SchedulerStepper.tsx
src/components/studies/scheduler/SessionStartTab.tsx
src/components/studies/scheduler/read-only-pages/ReadOnlyScheduler.tsx
src/components/studies/session-creator/SessionCreator.tsx
src/components/studies/studyHooks.ts
src/components/widgets/SideBarListItem.tsx
src/components/widgets/TopErrorBanner.tsx
src/routes_private.ts

@leonli33  -- just and FYI. A lot has changed

Complete refactor of study builder!

---

src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/modify/BatchEditForm.tsx
src/components/widgets/SideBarListItem.tsx
src/services/participants.service.ts

Participants no longer move tabs when edited.

Fix participant issue in Participant Manager

---

src/components/studies/launch/Launch.tsx
src/components/studies/scheduler/Duration.tsx
src/components/studies/scheduler/RepeatFrequency.tsx
src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx
src/components/studies/scheduler/SchedulingFormSection.tsx

Disable interval when occurrences is 1

---

src/components/studies/participants/ParticipantManager.tsx

Removed helper box.

---

src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx

Update Session Window addition feature

---

src/components/studies/scheduler/SessionStartTab.tsx

update 'spaces in events' error message

https://sagebionetworks.jira.com/browse/MTB-250

---

src/assets/study-builder-icons/hovered/launch_study_live_hover_icon.svg
src/assets/study-builder-icons/normal/launch_study_live_normal_icon.svg
src/components/studies/StudyLeftNav.tsx
src/components/studies/launch/Launch.tsx
src/components/studies/launch/LaunchAlerts.tsx
src/components/studies/sections.ts

editing 'launch' for live study

https://sagebionetworks.jira.com/browse/MTB-268

---

src/components/widgets/SideBarListItem.tsx

increase height for the access settings

https://sagebionetworks.jira.com/browse/MTB-269

---

src/components/studies/StudyTopNav.tsx
src/components/widgets/MobileDrawerMenuHeader.tsx

https://sagebionetworks.jira.com/browse/MTB-270

remove re-login on 'home' icon

---

src/components/studies/StudyBuilder.tsx
src/components/studies/passive-features/PassiveFeatures.tsx

https://sagebionetworks.jira.com/browse/MTB-266

change title on background recorders. different message if none

---

src/components/studies/scheduler/AssessmentList.tsx

https://sagebionetworks.jira.com/browse/MTB-314

remove 'randomized' option

---

src/components/studies/studyHooks.ts
src/helpers/utility.ts
src/services/participants.service.ts
src/services/study.service.ts

https://sagebionetworks.jira.com/browse/MTB-374

get all studies while getting study listing

---

src/components/studies/StudyBuilder.tsx
src/components/studies/app-design/AppDesign.tsx
src/components/studies/studyHooks.ts
src/services/study.service.ts

show server error for app design

---

src/components/studies/eventHooks.ts
src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/add/AddParticipants.tsx
src/components/studies/participants/add/AddSingleParticipant.tsx
src/components/studies/participants/add/AddSingleParticipantForm.tsx
src/components/studies/participants/add/ImportParticipantsInstuctions.tsx
src/components/studies/participants/csv/csvUtility.ts
src/components/studies/participants/grid/ParticipantTableGrid.tsx
src/components/studies/participants/modify/EditParticipantEventsForm.tsx
src/components/studies/participants/modify/EditParticipantForm.tsx
src/services/event.service.ts
src/services/participants.service.ts
src/services/schedule.service.ts

- add clientTimeZone to import and export
-  fix notes field

Edit Burst Events in PM

---

src/components/studies/app-design/LeadInvestigatorDropdown.tsx

https://sagebionetworks.jira.com/browse/MTB-362

fix 'principal' typo

---

src/components/studies/StudyTopNav.tsx

https://sagebionetworks.jira.com/browse/MTB-405

disable links to PM and adherence for non-live studies on mobile

---

src/components/studies/StudyTopNav.tsx
src/components/widgets/MobileDrawerMenuHeader.tsx

https://sagebionetworks.jira.com/browse/MTB-405

change the logo image for mobile menu and add hover state

---

src/components/studies/scheduler/Scheduler.tsx

https://sagebionetworks.jira.com/browse/MTB-403

fix(bursts): change events modal title

---

src/components/studies/preview/Preview.tsx

Create qr code from existing study demo intro and align indentation.

Create QR code for Demo All Assessment

---

src/components/adherence/participant-detail/AdherenceParticipant.tsx
src/components/adherence/participant-detail/AdherenceParticipantGrid.tsx
src/components/adherence/participant-detail/EditParticipantEvents.tsx
src/components/adherence/participants/AdherenceParticipantsGrid.tsx
src/components/adherence/styles.ts
src/components/studies/eventHooks.ts
src/components/widgets/ErrorDisplay.tsx
src/services/event.service.ts

- add adherence % to weekly grid
- move adherence events update to its own component
- service cleanup

Weekly and Participant adherence updates

---

src/components/adherence/DayDisplayForSession.tsx
src/components/adherence/TimeWindowPlotElement.tsx
src/components/adherence/adherenceUtility.ts
src/components/adherence/participant-detail/AdherenceParticipantGrid.tsx
src/components/adherence/participants/AdherenceParticipants.tsx
src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/ParticipantSearch.tsx
src/types/types.ts

- provide text for undefined start date
- add participant search box

Updates to Adherence

---

src/components/adherence/participant-detail/AdherenceParticipant.tsx
src/components/adherence/participant-detail/EditParticipantNotes.tsx

https://sagebionetworks.jira.com/browse/MTB-418
Let note field update and save. Format bottom fields.

Update bottom field for single participant adherence

---

src/components/studies/session-creator/SessionActionButtons.tsx
src/components/studies/session-creator/SessionCreator.tsx
src/components/studies/session-creator/sessionActions.ts

https://sagebionetworks.jira.com/browse/MTB-421

fix(sessionBuilder): don't assign duplicate symbol after session deleted

---

src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/csv/csvUtility.ts

@yjyoo773 - just FYI -- fixing a bug where the joined date does not get exported

fix(PM): export to include the joined date

---

src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx
src/components/studies/scheduler/StartDate.tsx

Removed gray background when hovering over pencil icon and have it change colors to white.
https://sagebionetworks.jira.com/browse/MTB-403

style(scheduler): change edit icon color when hovering

---

src/components/studies/session-creator/read-only-pages/ReadOnlySessionCreator.tsx

https://sagebionetworks.jira.com/browse/MTB-426

style(scheduler): change grid display to prevent cut off

---

src/components/studies/participants/grid/ParticipantTableGrid.tsx
src/services/participants.service.ts

https://sagebionetworks.jira.com/browse/MTB-429

Show health code for searched participants

---

src/components/adherence/participant-detail/AdherenceParticipant.tsx
src/components/adherence/participant-detail/EditParticipantEvents.tsx
src/components/adherence/participants/AdherenceParticipantsGrid.tsx
src/components/studies/participants/modify/EditParticipantEventsForm.tsx
src/services/participants.service.ts

1. Ping adhrence after adding participant and events update
2. Have first burst start at base event date
3. Make adherence events modal larger

Updates to adherence and participant events

---

src/components/studies/scheduler/timeline-plot/TimelineBurstPlot.tsx

https://sagebionetworks.jira.com/browse/MTB-434

fix(scheduler): show the burst bracket

---

src/components/adherence/participants/AdherenceParticipants.tsx
src/components/studies/StudyList.tsx
src/components/studies/participantHooks.ts
src/components/studies/participants/ParticipantManager.tsx
src/components/widgets/pagination/PageBox.tsx
src/components/widgets/pagination/PageSelector.tsx
src/components/widgets/pagination/TablePagination.tsx
src/services/adherence.service.ts

https://sagebionetworks.jira.com/browse/MTB-430

fix(pagination): change pagination index from 1 to 0

---

src/components/adherence/SessionLegend.tsx
src/components/adherence/TimeWindowPlotElement.tsx
src/components/adherence/participant-detail/AdherenceParticipantGrid.tsx
src/components/adherence/participant-detail/AdherenceSessionIcon.tsx
src/components/adherence/styles.ts
src/components/studies/participants/modify/EditParticipantEventsForm.tsx
src/components/studies/scheduler/Scheduler.tsx

https://sagebionetworks.jira.com/browse/MTB-437

Schedule and adherence fixes

---

src/components/studies/StudyList.tsx

https://sagebionetworks.jira.com/browse/MTB-432

fix(study): disable clicking generating duplicate study

---

src/components/studies/participants/ParticipantDeleteModal.tsx
src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/add/AddSingleParticipant.tsx
src/components/studies/participants/grid/ParticipantTableGrid.tsx
src/components/studies/participants/modify/BatchEditForm.tsx
src/components/studies/participants/modify/EditParticipantForm.tsx
src/components/studies/participants/modify/WithdrawParticipantForm.tsx

Create alert banner when error occurs while adding, withdrawing, editing, deleting, getting, or searching participants in participant manager.  
https://sagebionetworks.jira.com/browse/MTB-439

feat(PM): create error handling alerts for features in PM

---

src/components/adherence/participant-detail/AdherenceParticipant.tsx

https://sagebionetworks.jira.com/browse/MTB-436

style(adherence): add completed styling for completed participants

---

package.json
src/components/studies/participants/grid/ParticipantTableGrid.tsx
tsconfig.json
yarn.lock

Ellis, can you please pull in this PR, remove node_modules and try to build (yarn build) and run this code to see if it works for you.
Also, please try out the participant manager and see if grid is working ok for you (selection, and edit mostly)

chore:  update react scripts to 5.0

---

src/components/studies/preview/Preview.tsx
src/components/surveys/SurveyQuestion.tsx
src/components/surveys/Surveys.tsx
src/components/surveys/display/ChoiceQuestion.tsx
src/components/surveys/display/SurveyDisplay.tsx
src/components/surveys/sample.json
src/components/surveys/types.ts
src/components/widgets/DatePicker.tsx
src/routes_private.ts
src/services/participants.service.ts

https://sagebionetworks.jira.com/browse/BRIDGE-3245

Sharing scope update + surveys WIP

---

src/components/studies/preview/Preview.tsx
src/services/participants.service.ts

https://sagebionetworks.jira.com/browse/BRIDGE-3245

fix(PM): update sharing scope.

---

src/components/studies/participants/csv/csvUtility.ts
src/components/studies/participants/grid/ParticipantTableGrid.tsx
src/services/participants.service.ts
src/types/types.ts

https://sagebionetworks.jira.com/browse/BMC-329

fix(participants): display healthCode instead of id in grid

---

src/components/adherence/participants/AdherenceParticipantsGrid.tsx
src/components/adherence/participants/NextActivity.tsx

https://sagebionetworks.jira.com/browse/MTB-457

feat(adherence): up next

---

src/components/studies/participants/grid/ParticipantTableGrid.tsx
src/components/studies/participants/modify/EditParticipantEventsForm.tsx

https://sagebionetworks.jira.com/browse/MTB-488

fix(PM): remove editing of the first burst

---

src/components/studies/participants/add/ImportParticipantsInstuctions.tsx

https://sagebionetworks.jira.com/browse/MTB-465

fix(PM): upload instructions update

---

src/components/studies/eventHooks.ts
src/components/studies/participants/DialogContents.tsx
src/components/studies/participants/ParticipantDeleteModal.tsx
src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/add/AddGeneratedParticipant.tsx
src/components/studies/participants/grid/ParticipantTableGrid.tsx

https://sagebionetworks.jira.com/browse/MTB-464

fix(PM): fix error with deleting participants

---

src/components/adherence/participant-detail/AdherenceParticipant.tsx
src/components/adherence/participant-detail/EditParticipantEvents.tsx
src/components/studies/eventHooks.ts
src/components/studies/participantHooks.ts
src/components/studies/participants/DialogContents.tsx
src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/TimezoneDropdown.tsx
src/components/studies/participants/add/AddSingleParticipant.tsx
src/components/studies/participants/add/AddSingleParticipantForm.tsx
src/components/studies/participants/csv/csvUtility.ts
src/components/studies/participants/grid/ParticipantTableGrid.tsx
src/components/studies/participants/modify/BatchEditForm.tsx
src/components/studies/participants/modify/EditParticipantForm.tsx
src/components/widgets/BlackBorderDropdown.tsx
src/services/event.service.ts
src/types/types.ts

- Select All fix
-  Require timezone

Participant Manager cleanup and enhancement

---

src/style/theme.ts

https://sagebionetworks.jira.com/browse/MTB-431

fix(style): focused tabs should be the same color

---

src/components/widgets/StyledComponents.tsx

https://sagebionetworks.jira.com/browse/MTB-508

fix(style): increase padding between label and field

---

src/components/studies/participants/add/AddSingleParticipantForm.tsx
src/components/studies/participants/modify/EditParticipantForm.tsx

https://sagebionetworks.jira.com/browse/MTB-518

fix(events): only require timezone for studies with custom events

---

src/components/studies/StudyCard.tsx

https://sagebionetworks.jira.com/browse/MTB-511

fix(studies): get active participants number from adherence

---

src/components/studies/StudyList.tsx

…ating study with filters set
https://sagebionetworks.jira.com/browse/MTB-509

fix(studies): scroll on status filter change as a solution for duplication

---

src/components/studies/participants/add/AddSingleParticipant.tsx
src/components/studies/scheduler/ConfigureBurstTab.tsx

Don't require timezone if study has no custom events

---

src/components/adherence/participant-detail/AdherenceParticipant.tsx
src/components/studies/participantHooks.ts

https://sagebionetworks.jira.com/browse/MTB-513

fix(adherence): no device bug

---

src/services/access.service.ts
src/services/participants.service.ts

https://sagebionetworks.jira.com/browse/MTB-525

fix(access): set the users to be used for assessment as study preview as a 'review_user' group

---

src/components/adherence/participant-detail/AdditionalAdherenceParticipantInfo.tsx
src/components/studies/enrollment-type-selector/EnrollmentTypeSelector.tsx
src/types/types.ts

https://sagebionetworks.jira.com/browse/DIAN-556

---

src/components/adherence/DayDisplay.tsx
src/components/adherence/TimeWindowPlotElement.tsx
src/components/adherence/adherenceUtility.ts
src/components/adherence/participant-detail/AdherenceParticipant.tsx
src/components/adherence/participant-detail/AdherenceParticipantGrid.tsx
src/helpers/utility.ts
src/types/types.ts

https://sagebionetworks.jira.com/browse/DHP-119

add start time to session window for arc

---

src/components/account/AccountLogin.tsx
src/components/studies/StudyList.tsx
src/helpers/utility.ts
src/types/constants.ts
src/types/types.ts

@jay-hodgson, just FYI 
Login and verification integration is working. Login redirects correctly. Redirect from verification needs to be implemented
some MTB verification-related code can be found here: [in this commit](https://github.com/Sage-Bionetworks/mtb/commit/fd79c257afc478af6f4e2821be1e55a9a28d3ba0)

Login and validation integration with OneSage

---

src/components/studies/launch/AboutStudy.tsx
src/style/theme.ts

https://sagebionetworks.jira.com/browse/MTB-644

autocomplete color change and entry accepted onBlur

---

public/index.html
src/App.tsx
src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/GeneralContactAndSupportSection.tsx
src/components/studies/app-design/StudySummaryRoles.tsx
src/components/studies/app-design/phone/StudyPageBottomPhoneContent.tsx
src/components/studies/app-design/phone/StudyPageTopPhoneContent.tsx
src/components/studies/app-design/phone/WelcomeScreenPhoneContent.tsx
src/components/widgets/ErrorHandler.tsx
src/useTracking.ts

https://sagebionetworks.jira.com/browse/MTB-647

  add tracking to mtb studies

---

src/components/widgets/pagination/PageBox.tsx
src/components/widgets/pagination/PageSelector.tsx
src/components/widgets/pagination/TablePagination.tsx

https://sagebionetworks.jira.com/browse/MTB-717

rework paging

---

src/__test_utils/mocks/study.json
src/__test_utils/test_server/assessmentHandlers.ts
src/__test_utils/test_server/handlers.ts
src/__test_utils/test_server/scheduleHandlers.ts
src/services/study.service.test.ts
src/services/study.service.ts
src/types/types.ts

https://sagebionetworks.jira.com/browse/MTB-723

remove exporter configuration from copied study 

---

src/__test_utils/mocks/adherenceAlerts.json
src/components/studies/BannerInfo.ts
src/components/studies/StudyBuilder.tsx
src/components/studies/StudyBuilderHeader.tsx
src/components/studies/StudyLeftNav.tsx
src/components/studies/app-design/AppDesign.tsx
src/components/studies/app-design/phone/StudyPageTopPhoneContent.tsx
src/components/widgets/AlertBanner.tsx

https://sagebionetworks.jira.com/browse/DHP-251

Fix AppDesign number bug and change read-only banner

---

src/__test_utils/mocks/adherenceAlerts.json
src/components/adherence/Adherence.tsx
src/components/adherence/summary/AdherenceAlerts.tsx
src/components/adherence/summary/AdherenceSummary.tsx
src/components/studies/adherenceHooks.ts
src/mocks/handlers.ts
src/services/adherence.service.ts
src/types/constants.ts
src/types/types.ts

Work in progress for https://sagebionetworks.jira.com/browse/MTB-652

Researcher UI for Alerts

---

src/components/adherence/summary/AdherenceAlerts.tsx
src/components/studies/adherenceHooks.ts

updates to adherence alerts

---

src/components/studies/StudyList.tsx
src/components/widgets/AlertBanner.tsx

https://sagebionetworks.jira.com/browse/DHP-234

Add styled verify now banner

---

src/components/access-settings/AccessGrid.tsx
src/components/access-settings/AccessSettings.tsx
src/components/access-settings/MemberInvite.tsx
src/style/theme.ts

https://sagebionetworks.jira.com/browse/MTB-731
https://sagebionetworks.jira.com/browse/MTB-732
https://sagebionetworks.jira.com/browse/MTB-734
https://sagebionetworks.jira.com/browse/MTB-733

access settings fixed

---

src/components/access-settings/AccessSettings.tsx
src/style/theme.ts

https://sagebionetworks.jira.com/browse/MTB-734

remove from study styling

---

src/components/adherence/participant-detail/AdherenceAssessmentLevelReport.tsx
src/services/adherence.service.ts
src/types/types.ts

Adding live data for adherence.
Still need to get the session grouping working when more data is available
@jay-hodgson - adding you as a reviewer as an FYI

incorporating live data for adherence retail report

---

package.json
src/components/studies/scheduler/Scheduler.tsx
src/components/surveys/survey-design/left-panel/QuestionConfigs.tsx
src/components/surveys/survey-design/question-edit/QuestionEditPhone.tsx
src/components/surveys/survey-design/question-edit/QuestionEditRhs.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/FreeText.tsx
src/types/surveys.ts

Fixed the word wrapping and changed title, subtitle, detail to all scroll. Strictly speaking, this is not how the scrolling works on device, but the UI/UX is much better than the scrollviews inside scrollviews that you get with a max lines.
Also fixed a few of the issues that were low-hanging fruit discovered on Wednesday.
https://sagebionetworks.jira.com/browse/DHP-1047
https://sagebionetworks.jira.com/browse/DHP-1048
https://sagebionetworks.jira.com/browse/DHP-1077
https://sagebionetworks.jira.com/browse/DHP-1076

Survey fixes

---

.github/workflows/build-and-deploy.yaml

This PR updates the role to assume by the Github action (the old role has been changed to match the new org and repo).

IT-3231: Update role arn

---

src/components/surveys/survey-design/question-edit/QuestionEditRhs.tsx

https://sagebionetworks.jira.com/browse/DHP-1082
before: 
https://github.com/BridgeDigitalHealth/open-bridge-web/assets/26949006/515371de-dc1b-48fc-9ad6-933ba0c0de07
after: 
https://github.com/BridgeDigitalHealth/open-bridge-web/assets/26949006/86fe5757-ac20-4748-bd3d-60d8d2b6f8ed

DHP-1082: don't allow researcher to directly edit survey step identifier

---

src/services/assessment.service.ts

https://sagebionetworks.jira.com/browse/DHP-1110

DHP-1110 Mark an assessment as draft when making a copy

---

src/components/surveys/survey-design/question-edit/rhs-subcontrols/Year.test.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/YearRadioGroup.tsx

Saw Erin's comment on https://sagebionetworks.jira.com/browse/DHP-1079 and went ahead and fixed it.

Fix grammar for setting up year constraints

---

src/components/surveys/survey-design/IntroInfo.tsx
src/components/surveys/survey-design/SurveyDesign.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Completion.tsx

https://sagebionetworks.jira.com/browse/DHP-1087
Updated: Changed the copy. Now looks like this:

DHP-1087 Update copy on the completion screen and remove “Publish” button

---

src/components/surveys/survey-design/SurveyDesign.tsx

Move the banner to the main content using a container component.

Move ReadOnlyBanner to main content

---

src/App.tsx
src/SignInPage.tsx
src/__test_utils/test_server/handlers.ts
src/__test_utils/test_server/userHandlers.ts
src/components/account/AccountLogin.tsx
src/components/account/ResetPassword.test.tsx
src/components/account/ResetPassword.tsx
src/components/account/UsernamePasswordForm.tsx
src/components/widgets/AppTopNav.tsx
src/helpers/AuthContext.tsx
src/helpers/FeatureToggle.tsx
src/routes_public.ts
src/services/user.service.ts
src/types/constants.ts

https://sagebionetworks.jira.com/browse/DHP-1045
https://github.com/BridgeDigitalHealth/open-bridge-web/assets/26949006/0931ac7e-2517-4e19-9c84-e551c72ff838

DHP-1045: add ability to request password reset

---

package.json
src/components/account/ResetPassword.test.tsx
src/components/adherence/summary/AdherenceAlerts.test.tsx
src/components/studies/scheduler/Duration.test.tsx
src/components/studies/scheduler/SchedulableSingleSessionContainer.test.tsx
src/components/surveys/survey-branching/BranchingConfig.test.tsx
src/components/surveys/survey-design/IntroInfo.test.tsx
src/components/surveys/survey-design/left-panel/AddQuestionMenu.test.tsx
src/components/surveys/survey-design/question-edit/QuestionEditToolbar.test.tsx
src/components/surveys/survey-design/question-edit/SelectPhoneBottomMenu.test.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/Completion.test.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/Numeric.test.ts
src/components/surveys/survey-design/question-edit/phone-subcontrols/Select.test.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/SelectExtraActions.test.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/SurveyTitle.test.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Numeric.test.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Scale.test.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Select.test.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/SurveyTitle.test.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Time.test.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Year.test.tsx
src/components/widgets/pagination/TablePagination.test.tsx
yarn.lock

https://sagebionetworks.jira.com/browse/DHP-1123

DHP-1123: resolve act warnings in tests by using a single version of @testing-library/dom

---

src/components/surveys/survey-branching/BranchingConfig.tsx
src/components/surveys/survey-design/SurveyDesign.tsx
src/components/surveys/survey-design/left-panel/QuestionConfigs.tsx
src/components/surveys/survey-design/question-edit/SelectPhoneBottomMenu.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/Select.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Select.tsx
src/types/surveys.ts

- integer-type choices should be numbers and string values should be strings
- when changing the value, need to update survey rules and keep UI key map consistent
https://sagebionetworks.jira.com/browse/DHP-1128

DHP-1128 Fix question choice values and UI key mapping

---

src/components/assessments/AssessmentCard.tsx
src/components/assessments/AssessmentCardLegacy.tsx
src/components/assessments/AssessmentDetail.tsx
src/components/assessments/AssessmentImage.tsx
src/components/assessments/AssessmentLibraryWrapper.tsx
src/components/assessments/AssessmentSmall.tsx
src/components/studies/scheduler/ScheduleTimelineDisplay.tsx

https://sagebionetworks.jira.com/browse/DHP-1097

DHP-1097 Update assessment and survey card to match 2.0 designs

---

src/components/studies/DownloadTrigger.tsx
src/components/studies/StudyTopNav.tsx
src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/add/ImportParticipantsInstuctions.tsx
src/components/studies/study-data/StudyData.tsx
src/routes_private.ts
src/services/study.service.ts
src/types/constants.ts
src/types/types.ts

I can confirm that the CSV file is downloaded for the survey. 
https://github.com/BridgeDigitalHealth/open-bridge-web/assets/5649217/56885e16-2d4d-49aa-87da-7b3feda9c1ac

CSV scores and survey answer download
