BridgeDigitalHealth/open-bridge-web

src/services/participants.service.ts

@leonli33 - just FYI in case if affects your tests.
The externalId field is deprecated so we are using the externalId*s*  field mapping to get external id

update the service to get externalId from externalIds mapping

---

src/components/studies/StudyBuilder.tsx
src/components/studies/scheduler/IntroInfo.tsx
src/components/studies/scheduler/StudyStartDate.tsx

The screen now looks like:
When the height is shortened:
When the width is shortened:
On Mobile:

Fix study duration screen display based on screen size

---

src/components/studies/app-design/StudyPageBottomPhoneContent.tsx
src/components/studies/app-design/StudyPageTopPhoneContent.tsx

The section indicators on the AppDesign page used to be in the wrong positions when the user is on Safari. Made changes to CSS so now it looks identical to chrome.

Fixed Section Indicator Position Issue on Safari

---

src/components/studies/NavButtons.tsx
src/components/studies/StudyBuilder.tsx
src/components/studies/StudyLeftNav.tsx
src/components/studies/session-creator/SessionCreator.tsx
src/components/studies/session-creator/SingleSessionContainer.tsx

Looks like:
Also, when there is only one session remaining, revoke ability to delete the session:

Disable Nav menu when one session has no assessments

---

src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/ParticipantTableGrid.tsx
src/components/studies/participants/ParticipantTablePagination.tsx

Moved the pagination control into the participant manger 
- the reason for doing it is that we had several properties in the grid that were only there for the paging and it was polluting the component
- Instead i have moved the paging component directly into the manager and used the 'children' property to display it in the grid

refactor participant table pagination

---

src/components/studies/StudyTopNav.tsx
src/components/studies/participants/ParticipantManager.tsx
src/components/widgets/AppTopNav.tsx

1. MTB logo now redirects back to the "My Studies" page:
2. Extend the white background to the left in the participant manager:
3. Get rid of gap between participant list and study ID based on which tab is selected:

Changes requested by Lynn

---

src/components/studies/StudyCard.tsx
src/components/studies/StudyList.tsx

Now looks like: 
Resolves: https://sagebionetworks.jira.com/browse/MTB-177

Restyle study card menu

---

src/components/studies/StudyLeftNav.tsx
src/components/studies/scheduler/NotificationWindow.tsx
src/components/studies/session-creator/SingleSessionContainer.tsx

1. Add limitation to the number of characters that are able to be typed in the notification input fields to be 40:
2. Reduced opacity of the left nav menus in the study builder when they are disabled (opacity is now 0.3):
3. Got rid of scrollbar on the session container:
Resolves: https://sagebionetworks.jira.com/browse/MTB-175, https://sagebionetworks.jira.com/browse/MTB-176

Jira Issues

---

src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/ParticipantSearch.tsx

In the participant manager, when the tab is changed the search participant component is cleared.
Resolves: #256

Clear search when tab is changed.

---

src/components/studies/participants/ParticipantManager.tsx
src/components/studies/participants/ParticipantTableGrid.tsx

1. Hide send sms button
2. Rename "Participant ID" to "Log in ID" for the test participants tab
3. Remove phone number column from the Test Participants Tab
Looks like:

Restyle test accounts tab

---

src/components/studies/StudyBuilder.tsx
src/components/studies/launch/Launch.tsx
src/components/studies/scheduler/Scheduler.tsx
src/components/studies/scheduler/SessionStartTab.tsx

Looks like:
On error:
Resolves #340

Remove study burst tab and also add error handling to Define Session Start page

---

src/components/studies/participants/grid/ParticipantTableGrid.tsx

mtb-279
In participant manager, hide timezone column for studies without calendar events.

Hide timezone for studies without calendar event

---

src/components/studies/scheduler/Scheduler.tsx
src/components/studies/scheduler/read-only-pages/ReadOnlyScheduler.tsx

In read-only view the the burst session doesn't display the correct event

fix(scheduler): read only scheduler -- show the correct event

---

src/components/studies/app-design/AppDesign.tsx

Fix for logo upload button on AppDesign. 
When a logo is already uploaded and user clicks upload and cancels, causes circular spinner infinitely.

fix(appDesign): fix upload logo button to spin when cancelling upload

---

package.json
yarn.lock

Verified that after the change I could run it locally (via yarn start) and run an optimized build (yarn build).
https://github.com/Sage-Bionetworks/mtb/security/dependabot/49

PORTALS-2389 - force sub-dependencies to use minimatch ^3.1.2

---

src/components/studies/StudyBuilder.tsx
src/components/studies/scheduler/Duration.test.tsx
src/components/studies/scheduler/Duration.tsx
src/components/studies/scheduler/Scheduler.tsx

- close error banner after cancelling changes to a single session schedule
- change Duration to optionally restrict to a max number of digits and set input width accordingly

Scheduler fixes

---

src/components/studies/scheduler/NotificationTime.tsx
src/components/studies/scheduler/NotificationWindow.tsx
src/components/studies/scheduler/SchedulableSingleSessionContainer.test.tsx
src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx
src/components/studies/scheduler/SharedComponents.tsx

- don't allow initial notification to be deleted if a follow-up notification exists
- re-calculate multiday reminder offset when windowStartTime is changed
- add session scheduler tests - notifications

Add session scheduler tests - notifications

---

.github/workflows/build-and-deploy.yaml

Looks like the dry-run deploy succeeded, removing the parameter.

GH workflow: Remove dryrun

---

src/components/surveys/survey-design/question-edit/SelectPhoneBottomMenu.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Select.tsx

https://sagebionetworks.jira.com/browse/DHP-1033
There were a few bugs and UI/UX issues that I ended up adjusting along with disallowing "other" for a multiple choice question. Basically, there was no differentiation between enabled/disabled for "none of the above" and "all of the above" and that was confusing me. Also there was no explanation for why "none" and "all" weren't allowed for single choice but there was an explanation for "other" only being included for strings. The end result was to add a generic message for "hey, you've run out of special options to add to this question - nothing else applies".

[DHP-1033] Only include “+ Other” response if the type is a single choice string

---

src/components/studies/sections.tsx

Hide passive recorders by default.
Turns out that these were only hidden for Arc.

DHP-1068 Hide passive recorders by default

---

src/services/assessmentHooks.ts

https://sagebionetworks.jira.com/browse/DHP-1053
When copying, a copy of the assessment was being added with the identifier changed to "..." - the `guid`, which is the identifier used by Bridge, was not replaced by the "placeholder" and this copy was never removed.
Opened https://sagebionetworks.jira.com/browse/DHP-1093 to track improving the UI/UX for copying surveys

DHP-1053 Do not add an assessment to the list of assessments

---

src/components/surveys/survey-design/SurveyDesign.tsx
src/types/types.ts

https://sagebionetworks.jira.com/browse/DHP-1088
This is our short-term solution (until we design how to support localization) for setting the "label" for an assessment so that the title shown to the participant in the timeline matches the survey title page rather than the "name" shown to the researcher when scheduling or editing.

DHP-1088 Survey Builder - set ‘en’ label equal to the overview title

---

src/components/assessments/AssessmentLibrary.tsx
src/components/studies/StudyCard.tsx
src/components/studies/StudyList.tsx
src/components/surveys/SurveyCard.tsx
src/components/surveys/SurveyList.tsx
src/components/surveys/survey-design/question-edit/SelectPhoneBottomMenu.test.tsx
src/components/surveys/survey-design/question-edit/SelectPhoneBottomMenu.tsx
src/components/widgets/CardWithMenu.tsx
src/services/assessment.service.ts
src/services/assessmentHooks.ts
src/types/types.ts

https://sagebionetworks.jira.com/browse/DHP-1089 - The issue that I was originally looking at was that if you are on the survey list view and you select "Rename" from the menu, it doesn't work. Instead it was not hiding the menu and would navigate to the detail view for the survey.
I tried to match what it was doing on the Study list view (the code for "Survey Builder" list was copy/pasted from that code file), discovered a ton of warnings in tests and other discrepancies, and ended up down a bit of a renaming rabbit hole.
That said, the main "fixes" were:
- call through to services with the correct property names ("assessment", not "survey")
- don't navigate to the detail if the "Title" field is highlighted (ie. textfield rather than label)
Note: The UI/UX for a "rename" of a survey or …

DHP-1089 Fix "Rename" survey to actually allow renaming

---

src/components/studies/StudyBuilderHeader.tsx
src/components/surveys/survey-design/IntroInfo.tsx
src/components/surveys/survey-design/SurveyDesign.tsx
src/components/surveys/survey-design/left-panel/LeftPanel.tsx
src/components/surveys/survey-design/question-edit/QuestionEditPhone.tsx
src/components/surveys/survey-design/question-edit/QuestionEditRhs.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/Completion.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/Numeric.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/Scale.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/Select.tsx
src/components/surveys/survey-design/question-edit/phone-subcontrols/SurveyTitle.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Numeric.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Scale.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Select.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Time.test.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Time.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Year.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/YearRadioGroup.tsx
src/components/widgets/ReadOnlyBanner.tsx
src/services/assessmentHooks.ts

https://sagebionetworks.jira.com/browse/DHP-1095
https://sagebionetworks.jira.com/browse/DHP-1111
The `phase == 'published'` flag does not block editing the `Assessment`, only the `AssessmentConfig`, so it became a really poor user experience to view a published survey. This is not the cleanest UI/UX for handling this and it meant going through each component and a lot of code that looks *very* similar.
There are a number of "icky bits" that it would be nice to clean up "someday", most especially:
1. I tried to follow the existing naming convention used for studies of `isReadOnly` instead of the React naming convention of `readOnly`.
2. The React `readOnly` flag isn't honored on all controls (not sure why) so often I ended up using `if (isReadOnly) return` to exit the update functions …

read-only surveys

---

src/components/surveys/survey-branching/BranchingConfig.test.tsx
src/components/surveys/survey-branching/BranchingConfig.tsx
src/components/surveys/survey-branching/SurveyBranching.tsx

This uses the same blocking UI/UX as in the survey where drop-down and radio button elements are unchanged but cannot be edited. Turns out that b/c the Assessment and the AssessmentConfig are two different service calls, they have to be re-fetched (from cache) because the branching logic has multiple "routing" urls.

DHP-1114 Block changes to branching logic if read-only

---

src/components/surveys/survey-design/left-panel/QuestionConfigs.tsx
src/types/surveys.ts

1. “Free Text” wasn’t setting the character limit
2. Time questions were setting `allowFuture = false` by default which doesn’t make sense

Fix survey bugs discovered during testing

---

src/components/surveys/survey-design/SurveyDesign.tsx

This reverts commit 19e872f75a9969cf8906ed776285b7510db20e5e.
No idea why but apparently moving the "read-only" banner to across the top breaks text input field editing. For now, revert the change and just live with the undiscoverable banner. ¯\_(ツ)_/¯

Revert "Move ReadOnlyBanner to main content"

---

src/components/studies/enrollment-type-selector/EnrollmentTypeSelector.tsx

https://sagebionetworks.jira.com/browse/DHP-1109
Leaving the enrollment type for phones in the UI, but commented out.

Hide the option to enroll with a phone number

---

src/components/surveys/survey-design/IntroInfo.test.tsx
src/components/surveys/survey-design/IntroInfo.tsx
src/components/surveys/survey-design/SurveyDesign.tsx
src/components/surveys/survey-design/question-edit/QuestionEditPhone.test.tsx
src/components/surveys/survey-design/question-edit/QuestionEditPhone.tsx
src/types/surveys.ts

- Simplify the “skip rules” for surveys to include a global checkbox for making all questions required.
- Hide the “Review Instructions” navigation because it makes no sense.
- Default to *not* allowing participants to skip surveys
- Fix Question toggle visibility
- Fix “Save Changes” functionality to indicate that changes have been made to settings
- Add “Summary” text field at the bottom of the settings page
https://sagebionetworks.jira.com/browse/DHP-1132
https://sagebionetworks.jira.com/browse/DHP-1133

Simplify settings for the surveys

---

src/App.tsx
src/components/surveys/SurveyTopNav.tsx
src/components/surveys/survey-branching/SurveyBranching.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Completion.test.tsx
src/components/surveys/survey-design/question-edit/rhs-subcontrols/Completion.tsx
src/helpers/FeatureToggle.tsx

Found issues with the JSON config and how survey rules are being set up. In the interest of moving forward with other concerns, we're making branching logic read-only on production.

Making branching logic read-only in production
